name: similarity
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.8,<3.12
  - pip
  - pandas>=1.5.0,<2.0.0
  - numpy>=1.21.0,<2.0.0
  - pytz>=2024.0.0
  - python-dateutil>=2.8.0
  - pip:
    - torch>=2.0.0,<3.0.0
    - transformers>=4.30.0,<5.0.0
    - openpyxl>=3.1.0,<4.0.0
    - tqdm>=4.65.0,<5.0.0
    - huggingface-hub>=0.14.0,<1.0.0
    - filelock>=3.12.0,<4.0.0
    - safetensors>=0.4.0,<1.0.0
    - tokenizers>=0.13.0,<1.0.0
    - requests>=2.31.0,<3.0.0
    - pyyaml>=6.0.0,<7.0.0
    - regex>=2022.10.0,<2024.0.0
    - typing-extensions>=4.0.0,<5.0.0
